[world]
seed = ""
name = "Dark Shuffle"

[namespace]
default = "darkshuffle_s1"

[writers]
"darkshuffle_s1" = [
    "darkshuffle_s1-game_systems",
    "darkshuffle_s1-battle_systems",
    "darkshuffle_s1-season_systems",
    "darkshuffle_s1-draft_systems",
    "darkshuffle_s1-map_systems",
    "darkshuffle_s1-config_systems",
]

[env]
world_address = "0x044c4ffdf401b1fe8c4b75eb8c8076d28dd91940ea31de93814dc82e1410b86e"
world_block = 1014817
