[package]
cairo-version = "=2.8.4"
name = "darkshuffle"
version = "1.0.0"

[cairo]
sierra-replace-ids = true

[dependencies]
starknet = "2.8.4"
cartridge_vrf = { git = "https://github.com/cartridge-gg/vrf" }
openzeppelin = { git = "https://github.com/OpenZeppelin/cairo-contracts.git", rev = "a13bae3" }
dojo = { git = "https://github.com/dojoengine/dojo", tag = "v1.0.5" }
achievement = { git = "https://github.com/cartridge-gg/arcade", tag = "v1.0.5" }

[dev-dependencies]
dojo_cairo_test = { git = "https://github.com/dojoengine/dojo.git", tag = "v1.0.5" }

[[target.starknet-contract]]
build-external-contracts = [
    "dojo::world::world_contract::world",
    "achievement::events::index::e_TrophyCreation",
    "achievement::events::index::e_TrophyProgression",
]

[tool.fmt]
sort-module-level-items = true
max-line-length = 120

[profile.sepolia]
[profile.slot]
[profile.mainnet]